dbca-wa/pbs

Procfile, manage.py, pbs/prescription/admin.py, pbs/prescription/models.py, pbs_project/wsgi.py, requirements.txt
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/pbs/1)
=> Update missing req's, removed Procfile.

pbs/prescription/admin.py, pbs/review/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/pbs/3)
=> Day of burn review: alter queryset to show only prescriptions with approval not in the past

pbs/prescription/templatetags/prescription_tags.py, templates/latex/base.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/pbs/4)
=> Fixed DPaW logo issue in PDF header

templates/latex/sections/sectionb7.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/pbs/5)
=> Fixed Footer issue

templates/latex/sections/sectionb7.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/pbs/6)
=> fixed Section 7 footer

templates/latex/parts/form268a.tex, templates/latex/parts/form268a_rdo.tex, templates/latex/parts/form268b.tex, templates/latex/parts/form268b_rdo.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/pbs/10)
=> 268 pdfs: remove sentby on a/b, remove sdo approval on RDO versions

pbs/review/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/pbs/11)
=> review: fix bug with rdo 268 pdf queries for listing acknowledgements

pbs/review/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/pbs/12)
=> update dailyburns view sql, burn_target_date format, location

pbs/review/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/pbs/13)
=> review: add forest blocks to location

pbs/review/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/pbs/14)
=> review: update view to replace NULLs with blank text strings

pbs/review/models.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/pbs/15)
=> review: fixed location reference in daily burns view

pbs/prescription/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/pbs/16)
=> add export burn summary to csv action

pbs/prescription/models.py, templates/admin/prescription/prescription/approval.html, templates/admin/prescription/prescription/detail.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/pbs/17)
=> approval valid to default removed, added calendar widget

pbs/prescription/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/pbs/18)
=> add area treatment % to burn summary csv

pbs/document/migrations/0004_auto__chg_field_documenttag_category__chg_field_document_category__chg.py, pbs/document/models.py, pbs/implementation/migrations/0020_auto__chg_field_edgingplan_fuel_type__chg_field_edgingplan_prescriptio.py, pbs/implementation/models.py, pbs/migrations/0002_auto__chg_field_profile_region__chg_field_profile_district.py, pbs/models.py, pbs/prescription/admin.py, pbs/prescription/migrations/0026_auto__chg_field_approval_prescription__chg_field_briefingchecklist_pre.py, pbs/prescription/models.py, pbs/report/migrations/0006_auto__chg_field_areaachievement_prescription__chg_field_postburncheckl.py, pbs/report/models.py, pbs/review/migrations/0010_auto__chg_field_aircraftapproval_user__chg_field_aircraftapproval_airc.py, pbs/review/models.py, pbs/risk/migrations/0013_auto__chg_field_contingencynotification_contingency__chg_field_context.py, pbs/risk/models.py, pbs/stakeholder/migrations/0004_auto__chg_field_notification_prescription__chg_field_criticalstakehold.py, pbs/stakeholder/models.py, templates/latex/parts/form268b.tex, templates/latex/parts/form268b_rdo.tex
- 268b bushfire id column header
- on_delete protect for endorsingrole
- review but not endorse functionality change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/pbs/19)
=> minor changes to 268b pdf, endorsement fixes

pbs/review/admin.py, pbs/review/forms.py, templates/admin/review/prescribedburn/change_form.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/22)
=> Add new filter 'include_final_report' when load bushfire from bfrs.

pbs/review/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/23)
=> PBS annual indicative burn program link check trtd_area is a float

pbs/review/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/24)
=> Update admin.py - disable verify SSL cert for Add Bushfire BFRS lookup request

pbs/review/forms.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/25)
=> Update forms.py - disable verify SSL cert for Add Bushfire BFRS lookup request

pbs/review/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/27)
=> Update admin.py - hotfix in prod

pbs/review/forms.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/26)
=> Update forms.py - hotfix in prod

pbs/scripts/update_burn_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/29)
=> EOFY script fix for import application data

requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/31)
=> Pin Markdown library to 2.4.1 (current prod version).

pbs/prescription/actions.py, pbs/prescription/admin.py, pbs/review/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/34)
=> latexmk's commad option '-cd' is replaced with '--outdir' in new version

Dockerfile, pbs/review/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/35)
=> Run container as www-data. Fixed latexmk clean up step.

pbs/review/models.py
…
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/36)
=> Change the model 'AnnualIndicativeBurnProgram' to an unmanaged model and also comment out some unused columns

pbs/prescription/admin.py, pbs_project/settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/37)
=> Use --incognito flag with ffsend, increment project version to 1.6.2.

gunicorn.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/38)
=> Add timeout=600 to gunicorn.ini

Dockerfile, pbs/document/fields.py, pbs_project/settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/39)
=> Bugfix: fix error when uploading images as document (PDF conversion issue)

pbs_project/settings.py, templates/admin/base.html, templates/admin/risk/register/change_list.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/40)
=> Update URL to FMSB Fire manuals page (part A6) plus footer text

pbs/prescription/admin.py, pbs_project/settings.py, requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/43)
=> Updates to packages, fix to enforce --download-limit in ffsend command.

templates/admin/implementation/roadsegment/change_list.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/48)
=> ePFP update

README.md, pbs/review/admin.py, pbs/review/forms.py, pbs/review/models.py, pbs_project/settings.py, templates/admin/epfp_daily_burn_program.html, templates/latex/parts/form268a.tex, templates/latex/parts/form268a_rdo.tex, templates/latex/parts/form268b.tex, templates/latex/parts/form268b_rdo.tex, templates/latex/parts/form268c.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/44)
=> Completed work adding 'monitored' to active status levels

pbs/document/utils.py, pbs/prescription/actions.py, pbs/prescription/admin.py, pbs/prescription/models.py, pbs/utils/__init__.py, pbs/utils/pdf.py, pbs_project/settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/46)
=> Create PDF of burn plan upon approval, roll-over and closure

pbs/static/webmaps/indicativeburnprogram.html, pbs/static/webmaps/todaysburns.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/51)
=> Static web maps

pbs/static/webmaps/indicativeburnprogram.html, pbs/static/webmaps/todaysburns.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/53)
=> cleaned up pageload and syntax highlighting

pbs/static/webmaps/indicativeburnprogram.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/54)
=> display indicitive burns count

Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/88)
=> Missing Default Value for Docker Build

pbs/implementation/models.py, pbs/prescription/tests/test_functional.py, pbs/utils/pdf.py, pbs_project/settings.py, templates/latex/base.tex, templates/latex/base_form268.tex, templates/latex/base_form301.tex, templates/latex/form-sign-inspection-and-surveillance-form.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/96)
=> Update form-sign-inspection-and-surveillance-form.tex to show 2021 TCD names

.gitignore, Dockerfile, make_docker_image.sh, pbs/prescription/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/98)
=> fixed 'cvs export' issue and added git_history

pbs/scripts/update_burn_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/pbs/100)
=> Updated update_burn_data script to include tab 3b (apply_corp_approval)

.devcontainer/devcontainer.json, pbs/prescription/management/commands/monitor_prescription_archives.py, pbs/prescription/models.py, pbs_project/settings.py
- Adds a real time email alert when the system fails to generate an archive pdf
- Adds a management command that generates a .csv file of archiving issue and attaches it to an email
- Emails are sent to comma list of addresses specified in the NOTIFICATION_EMAIL environment variable
- If NOTIFICATION_EMAIL is not set, issues are logged to console (and will end up in rancher/k8s logs)
=> Prescription Archive Monitoring

pbs/prescription/management/commands/monitor_prescription_archives.py
Attempt to fix issue with monitoring management command
=> Open file before calling read.
